apiVersion: v1
kind: Service
metadata:
  name: rp-ml-api-postgres
  namespace: default
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: rp-ml-api-postgres
  type: ClusterIP
