# Generated by Django 2.1 on 2018-08-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('message_date', models.CharField(max_length=150)),
                ('flow', models.CharField(max_length=150)),
                ('model_tag', models.CharField(max_length=150, null=True)),
                ('user_tag', models.CharField(max_length=150, null=True)),
                ('id_message', models.IntegerField()),
                ('id_rp_user', models.IntegerField()),
                ('id_bot', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(max_length=150),
        ),
    ]
