# Generated by Django 2.1 on 2018-09-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_auto_20180903_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmessage',
            name='id_message',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='id_message_response',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='id_rp_user',
            field=models.CharField(max_length=150),
        ),
    ]
