# Generated by Django 2.1 on 2018-09-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_auto_20180911_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_in_training',
            field=models.BooleanField(default=True),
        ),
    ]
